# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/key_control_led_GPIO_EMIO.xdc

# Block Designs: bd/ps_design/ps_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_design || ORIG_REF_NAME==ps_design}]

# IP: bd/ps_design/ip/ps_design_processing_system7_0_0/ps_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_design_processing_system7_0_0 || ORIG_REF_NAME==ps_design_processing_system7_0_0}]

# XDC: bd/ps_design/ps_design_ooc.xdc
