# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio_pins.xdc

# Block Designs: bd/gpio_design/gpio_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design || ORIG_REF_NAME==gpio_design} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_processing_system7_0_0/gpio_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_processing_system7_0_0 || ORIG_REF_NAME==gpio_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_axi_gpio_0_0/gpio_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_0 || ORIG_REF_NAME==gpio_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_axi_gpio_0_1/gpio_design_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_1 || ORIG_REF_NAME==gpio_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_xbar_0/gpio_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_xbar_0 || ORIG_REF_NAME==gpio_design_xbar_0} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_auto_pc_0/gpio_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_auto_pc_0 || ORIG_REF_NAME==gpio_design_auto_pc_0} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_ps7_0_axi_periph_0/gpio_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==gpio_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gpio_design/ip/gpio_design_rst_ps7_0_50M_0/gpio_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==gpio_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_processing_system7_0_0/gpio_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_processing_system7_0_0 || ORIG_REF_NAME==gpio_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_0/gpio_design_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_0 || ORIG_REF_NAME==gpio_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_0/gpio_design_axi_gpio_0_0_ooc.xdc

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_0/gpio_design_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_0 || ORIG_REF_NAME==gpio_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_1/gpio_design_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_1 || ORIG_REF_NAME==gpio_design_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_1/gpio_design_axi_gpio_0_1_ooc.xdc

# XDC: bd/gpio_design/ip/gpio_design_axi_gpio_0_1/gpio_design_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_axi_gpio_0_1 || ORIG_REF_NAME==gpio_design_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_xbar_0/gpio_design_xbar_0_ooc.xdc

# XDC: bd/gpio_design/ip/gpio_design_auto_pc_0/gpio_design_auto_pc_0_ooc.xdc

# XDC: bd/gpio_design/ip/gpio_design_rst_ps7_0_50M_0/gpio_design_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==gpio_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_rst_ps7_0_50M_0/gpio_design_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpio_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==gpio_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/gpio_design/ip/gpio_design_rst_ps7_0_50M_0/gpio_design_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/gpio_design/gpio_design_ooc.xdc
