# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.cache/wt [current_project]
set_property parent.project_path C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/hdl/design_axi_cdma_wrapper.v
add_files C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/design_axi_cdma.bd
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_processing_system7_0_0/design_axi_cdma_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_axi_cdma_0_0/design_axi_cdma_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_axi_cdma_0_0/design_axi_cdma_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_axi_timer_0_0/design_axi_cdma_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_axi_timer_0_0/design_axi_cdma_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_rst_ps7_0_50M_0/design_axi_cdma_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_rst_ps7_0_50M_0/design_axi_cdma_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_rst_ps7_0_50M_0/design_axi_cdma_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_xbar_0/design_axi_cdma_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_xbar_1/design_axi_cdma_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_ds_0/design_axi_cdma_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_ds_0/design_axi_cdma_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_pc_0/design_axi_cdma_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_ds_1/design_axi_cdma_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_ds_1/design_axi_cdma_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_pc_1/design_axi_cdma_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/ip/design_axi_cdma_auto_pc_2/design_axi_cdma_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/design_axi_cdma_ooc.xdc]
set_property is_locked true [get_files C:/Users/mi/Desktop/Programma/ZYNQ/XC7Z020_240_ES_AXI_CDMA/XC7Z020_240_ES_AXI_CDMA.srcs/sources_1/bd/design_axi_cdma/design_axi_cdma.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_axi_cdma_wrapper -part xc7z020clg400-2


write_checkpoint -force -noxdef design_axi_cdma_wrapper.dcp

catch { report_utilization -file design_axi_cdma_wrapper_utilization_synth.rpt -pb design_axi_cdma_wrapper_utilization_synth.pb }
