set_property PACKAGE_PIN H17 [get_ports {axi_gpio_tri_io[1]}]
set_property PACKAGE_PIN B20 [get_ports {axi_gpio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {axi_gpio_tri_io[1]}]
set_property PACKAGE_PIN G14 [get_ports {emio_gpio_tri_io[0]}]
set_property PACKAGE_PIN C20 [get_ports {emio_gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emio_gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emio_gpio_tri_io[0]}]
