# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lcd_pins.xdc

# Block Designs: bd/lcd_design/lcd_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design || ORIG_REF_NAME==lcd_design}]

# IP: bd/lcd_design/ip/lcd_design_processing_system7_0_0/lcd_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_processing_system7_0_0 || ORIG_REF_NAME==lcd_design_processing_system7_0_0}]

# IP: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0}]

# IP: bd/lcd_design/ip/lcd_design_v_tc_0_0/lcd_design_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_v_tc_0_0 || ORIG_REF_NAME==lcd_design_v_tc_0_0}]

# IP: bd/lcd_design/ip/lcd_design_v_axi4s_vid_out_0_0/lcd_design_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==lcd_design_v_axi4s_vid_out_0_0}]

# IP: bd/lcd_design/ip/lcd_design_rgb2lcd_0_0/lcd_design_rgb2lcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_rgb2lcd_0_0 || ORIG_REF_NAME==lcd_design_rgb2lcd_0_0}]

# IP: bd/lcd_design/ip/lcd_design_axi_dynclk_0_0/lcd_design_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_dynclk_0_0 || ORIG_REF_NAME==lcd_design_axi_dynclk_0_0}]

# IP: bd/lcd_design/ip/lcd_design_axi_mem_intercon_0/lcd_design_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_mem_intercon_0 || ORIG_REF_NAME==lcd_design_axi_mem_intercon_0}]

# IP: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_0/lcd_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_0}]

# IP: bd/lcd_design/ip/lcd_design_ps7_0_axi_periph_0/lcd_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==lcd_design_ps7_0_axi_periph_0}]

# IP: bd/lcd_design/ip/lcd_design_xbar_0/lcd_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_xbar_0 || ORIG_REF_NAME==lcd_design_xbar_0}]

# IP: bd/lcd_design/ip/lcd_design_xlconcat_0_0/lcd_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_xlconcat_0_0 || ORIG_REF_NAME==lcd_design_xlconcat_0_0}]

# IP: bd/lcd_design/ip/lcd_design_auto_pc_0/lcd_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_auto_pc_0 || ORIG_REF_NAME==lcd_design_auto_pc_0}]

# IP: bd/lcd_design/ip/lcd_design_auto_pc_1/lcd_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_auto_pc_1 || ORIG_REF_NAME==lcd_design_auto_pc_1}]

# XDC: bd/lcd_design/ip/lcd_design_processing_system7_0_0/lcd_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_processing_system7_0_0 || ORIG_REF_NAME==lcd_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_v_tc_0_0/lcd_design_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_v_tc_0_0 || ORIG_REF_NAME==lcd_design_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/lcd_design/ip/lcd_design_v_tc_0_0/lcd_design_v_tc_0_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_v_axi4s_vid_out_0_0/lcd_design_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==lcd_design_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/lcd_design/ip/lcd_design_v_axi4s_vid_out_0_0/lcd_design_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_0/lcd_design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_0/lcd_design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_0/lcd_design_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_xbar_0/lcd_design_xbar_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_auto_pc_0/lcd_design_auto_pc_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_auto_pc_1/lcd_design_auto_pc_1_ooc.xdc

# XDC: bd/lcd_design/lcd_design_ooc.xdc
