# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lcd_pins.xdc

# Block Designs: bd/lcd_design/lcd_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design || ORIG_REF_NAME==lcd_design} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_processing_system7_0_0/lcd_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_processing_system7_0_0 || ORIG_REF_NAME==lcd_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_v_tc_0_0/lcd_design_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_v_tc_0_0 || ORIG_REF_NAME==lcd_design_v_tc_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_v_axi4s_vid_out_0_0/lcd_design_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==lcd_design_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_rgb2lcd_0_0/lcd_design_rgb2lcd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_rgb2lcd_0_0 || ORIG_REF_NAME==lcd_design_rgb2lcd_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_axi_dynclk_0_0/lcd_design_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_dynclk_0_0 || ORIG_REF_NAME==lcd_design_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/lcd_design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_axi_smc_0 || ORIG_REF_NAME==lcd_design_axi_smc_0} -quiet] -quiet

# Block Designs: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/bd_097e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_0/bd_097e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_1/bd_097e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_2/bd_097e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_3/bd_097e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_4/bd_097e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_5/bd_097e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_6/bd_097e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_7/bd_097e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_8/bd_097e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_9/bd_097e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_2/lcd_design_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_2 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_xbar_0/lcd_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_xbar_0 || ORIG_REF_NAME==lcd_design_xbar_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_ps7_0_axi_periph_2/lcd_design_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_ps7_0_axi_periph_2 || ORIG_REF_NAME==lcd_design_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_xlconcat_0_0/lcd_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_xlconcat_0_0 || ORIG_REF_NAME==lcd_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/lcd_design/ip/lcd_design_auto_pc_0/lcd_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lcd_design_auto_pc_0 || ORIG_REF_NAME==lcd_design_auto_pc_0} -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_processing_system7_0_0/lcd_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_processing_system7_0_0 || ORIG_REF_NAME==lcd_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_axi_vdma_0_0 || ORIG_REF_NAME==lcd_design_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_axi_vdma_0_0/lcd_design_axi_vdma_0_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_v_tc_0_0/lcd_design_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_v_tc_0_0 || ORIG_REF_NAME==lcd_design_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_v_axi4s_vid_out_0_0/lcd_design_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==lcd_design_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_1/bd_097e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_1/bd_097e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_5/bd_097e_s00a2s_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_6/bd_097e_sarn_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_7/bd_097e_srn_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/bd_0/ip/ip_8/bd_097e_m00s2a_0_ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_axi_smc_0/ooc.xdc

# XDC: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_2/lcd_design_rst_ps7_0_100M_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_2 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_rst_ps7_0_100M_2/lcd_design_rst_ps7_0_100M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==lcd_design_rst_ps7_0_100M_2 || ORIG_REF_NAME==lcd_design_rst_ps7_0_100M_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/lcd_design/ip/lcd_design_auto_pc_0/lcd_design_auto_pc_0_ooc.xdc

# XDC: bd/lcd_design/lcd_design_ooc.xdc
