// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Dilate.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Dilate::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Dilate::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> Dilate::ap_ST_fsm_state1 = "1";
const sc_lv<4> Dilate::ap_ST_fsm_state2 = "10";
const sc_lv<4> Dilate::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> Dilate::ap_ST_fsm_state7 = "1000";
const sc_lv<32> Dilate::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Dilate::ap_const_boolean_1 = true;
const sc_lv<32> Dilate::ap_const_lv32_2 = "10";
const bool Dilate::ap_const_boolean_0 = false;
const sc_lv<1> Dilate::ap_const_lv1_1 = "1";
const sc_lv<1> Dilate::ap_const_lv1_0 = "0";
const sc_lv<32> Dilate::ap_const_lv32_1 = "1";
const sc_lv<10> Dilate::ap_const_lv10_0 = "0000000000";
const sc_lv<32> Dilate::ap_const_lv32_3 = "11";
const sc_lv<11> Dilate::ap_const_lv11_0 = "00000000000";
const sc_lv<10> Dilate::ap_const_lv10_302 = "1100000010";
const sc_lv<10> Dilate::ap_const_lv10_1 = "1";
const sc_lv<10> Dilate::ap_const_lv10_300 = "1100000000";
const sc_lv<32> Dilate::ap_const_lv32_9 = "1001";
const sc_lv<9> Dilate::ap_const_lv9_0 = "000000000";
const sc_lv<2> Dilate::ap_const_lv2_1 = "1";
const sc_lv<2> Dilate::ap_const_lv2_2 = "10";
const sc_lv<11> Dilate::ap_const_lv11_402 = "10000000010";
const sc_lv<11> Dilate::ap_const_lv11_1 = "1";
const sc_lv<32> Dilate::ap_const_lv32_A = "1010";
const sc_lv<12> Dilate::ap_const_lv12_FFF = "111111111111";
const sc_lv<10> Dilate::ap_const_lv10_3FF = "1111111111";
const sc_lv<32> Dilate::ap_const_lv32_B = "1011";
const sc_lv<2> Dilate::ap_const_lv2_3 = "11";
const sc_lv<8> Dilate::ap_const_lv8_0 = "00000000";

Dilate::Dilate(sc_module_name name) : sc_module(name), mVcdFile(0) {
    k_buf_0_val_3_U = new FAST_t_opr_k_buf_dEe("k_buf_0_val_3_U");
    k_buf_0_val_3_U->clk(ap_clk);
    k_buf_0_val_3_U->reset(ap_rst);
    k_buf_0_val_3_U->address0(k_buf_0_val_3_address0);
    k_buf_0_val_3_U->ce0(k_buf_0_val_3_ce0);
    k_buf_0_val_3_U->q0(k_buf_0_val_3_q0);
    k_buf_0_val_3_U->address1(k_buf_0_val_3_address1);
    k_buf_0_val_3_U->ce1(k_buf_0_val_3_ce1);
    k_buf_0_val_3_U->we1(k_buf_0_val_3_we1);
    k_buf_0_val_3_U->d1(p_src_data_stream_V_dout);
    k_buf_0_val_4_U = new FAST_t_opr_k_buf_dEe("k_buf_0_val_4_U");
    k_buf_0_val_4_U->clk(ap_clk);
    k_buf_0_val_4_U->reset(ap_rst);
    k_buf_0_val_4_U->address0(k_buf_0_val_4_address0);
    k_buf_0_val_4_U->ce0(k_buf_0_val_4_ce0);
    k_buf_0_val_4_U->q0(k_buf_0_val_4_q0);
    k_buf_0_val_4_U->address1(k_buf_0_val_4_address1);
    k_buf_0_val_4_U->ce1(k_buf_0_val_4_ce1);
    k_buf_0_val_4_U->we1(k_buf_0_val_4_we1);
    k_buf_0_val_4_U->d1(k_buf_0_val_4_d1);
    k_buf_0_val_5_U = new FAST_t_opr_k_buf_dEe("k_buf_0_val_5_U");
    k_buf_0_val_5_U->clk(ap_clk);
    k_buf_0_val_5_U->reset(ap_rst);
    k_buf_0_val_5_U->address0(k_buf_0_val_5_address0);
    k_buf_0_val_5_U->ce0(k_buf_0_val_5_ce0);
    k_buf_0_val_5_U->q0(k_buf_0_val_5_q0);
    k_buf_0_val_5_U->address1(k_buf_0_val_5_address1);
    k_buf_0_val_5_U->ce1(k_buf_0_val_5_ce1);
    k_buf_0_val_5_U->we1(k_buf_0_val_5_we1);
    k_buf_0_val_5_U->d1(k_buf_0_val_5_d1);
    doCorner_mux_32_8ocq_U31 = new doCorner_mux_32_8ocq<1,1,8,8,8,2,8>("doCorner_mux_32_8ocq_U31");
    doCorner_mux_32_8ocq_U31->din0(src_kernel_win_0_va_6_fu_144);
    doCorner_mux_32_8ocq_U31->din1(ap_var_for_const0);
    doCorner_mux_32_8ocq_U31->din2(ap_var_for_const0);
    doCorner_mux_32_8ocq_U31->din3(col_assign_1_t_fu_474_p2);
    doCorner_mux_32_8ocq_U31->dout(tmp_49_fu_479_p5);
    doCorner_mux_32_8ocq_U32 = new doCorner_mux_32_8ocq<1,1,8,8,8,2,8>("doCorner_mux_32_8ocq_U32");
    doCorner_mux_32_8ocq_U32->din0(right_border_buf_0_1_fu_152);
    doCorner_mux_32_8ocq_U32->din1(ap_var_for_const0);
    doCorner_mux_32_8ocq_U32->din2(ap_var_for_const0);
    doCorner_mux_32_8ocq_U32->din3(col_assign_1_t_fu_474_p2);
    doCorner_mux_32_8ocq_U32->dout(tmp_50_fu_498_p5);
    doCorner_mux_32_8ocq_U33 = new doCorner_mux_32_8ocq<1,1,8,8,8,2,8>("doCorner_mux_32_8ocq_U33");
    doCorner_mux_32_8ocq_U33->din0(right_border_buf_0_s_fu_148);
    doCorner_mux_32_8ocq_U33->din1(ap_var_for_const0);
    doCorner_mux_32_8ocq_U33->din2(ap_var_for_const0);
    doCorner_mux_32_8ocq_U33->din3(col_assign_1_t_fu_474_p2);
    doCorner_mux_32_8ocq_U33->dout(tmp_51_fu_517_p5);
    doCorner_mux_32_8ocq_U34 = new doCorner_mux_32_8ocq<1,1,8,8,8,2,8>("doCorner_mux_32_8ocq_U34");
    doCorner_mux_32_8ocq_U34->din0(col_buf_0_val_0_0_fu_491_p3);
    doCorner_mux_32_8ocq_U34->din1(col_buf_0_val_1_0_fu_510_p3);
    doCorner_mux_32_8ocq_U34->din2(col_buf_0_val_2_0_fu_529_p3);
    doCorner_mux_32_8ocq_U34->din3(row_assign_7_1_t_reg_841);
    doCorner_mux_32_8ocq_U34->dout(tmp_52_fu_551_p5);
    doCorner_mux_32_8ocq_U35 = new doCorner_mux_32_8ocq<1,1,8,8,8,2,8>("doCorner_mux_32_8ocq_U35");
    doCorner_mux_32_8ocq_U35->din0(col_buf_0_val_0_0_fu_491_p3);
    doCorner_mux_32_8ocq_U35->din1(col_buf_0_val_1_0_fu_510_p3);
    doCorner_mux_32_8ocq_U35->din2(col_buf_0_val_2_0_fu_529_p3);
    doCorner_mux_32_8ocq_U35->din3(row_assign_7_2_t_reg_846);
    doCorner_mux_32_8ocq_U35->dout(tmp_57_fu_569_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ImagLoc_x_cast_fu_372_p2);
    sensitive << ( tmp_55_fu_362_p1 );

    SC_METHOD(thread_ImagLoc_x_fu_366_p2);
    sensitive << ( t_V_4_cast_fu_330_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_predicate_op94_read_state4 );
    sensitive << ( ap_predicate_op102_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_predicate_op94_read_state4 );
    sensitive << ( ap_predicate_op102_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_predicate_op94_read_state4 );
    sensitive << ( ap_predicate_op102_read_state4 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_predicate_op94_read_state4 );
    sensitive << ( ap_predicate_op102_read_state4 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );

    SC_METHOD(thread_ap_condition_635);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_860 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond460_i_i_fu_334_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_operation_100);
    sensitive << ( ap_predicate_op100_store_state4 );

    SC_METHOD(thread_ap_enable_operation_101);
    sensitive << ( ap_predicate_op101_store_state4 );

    SC_METHOD(thread_ap_enable_operation_103);
    sensitive << ( ap_predicate_op103_store_state4 );

    SC_METHOD(thread_ap_enable_operation_68);
    sensitive << ( exitcond460_i_i_fu_334_p2 );

    SC_METHOD(thread_ap_enable_operation_70);
    sensitive << ( exitcond460_i_i_fu_334_p2 );

    SC_METHOD(thread_ap_enable_operation_72);
    sensitive << ( exitcond460_i_i_fu_334_p2 );

    SC_METHOD(thread_ap_enable_operation_84);

    SC_METHOD(thread_ap_enable_operation_88);

    SC_METHOD(thread_ap_enable_operation_91);

    SC_METHOD(thread_ap_enable_operation_95);
    sensitive << ( ap_predicate_op95_store_state4 );

    SC_METHOD(thread_ap_enable_operation_96);
    sensitive << ( ap_predicate_op96_store_state4 );

    SC_METHOD(thread_ap_enable_operation_98);
    sensitive << ( ap_predicate_op98_store_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_state3_pp0_iter0_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_enable_state4_pp0_iter1_stage0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_predicate_op100_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );

    SC_METHOD(thread_ap_predicate_op101_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );

    SC_METHOD(thread_ap_predicate_op102_read_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );

    SC_METHOD(thread_ap_predicate_op103_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );

    SC_METHOD(thread_ap_predicate_op94_read_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );

    SC_METHOD(thread_ap_predicate_op95_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_39_reg_827 );

    SC_METHOD(thread_ap_predicate_op96_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_39_reg_827 );

    SC_METHOD(thread_ap_predicate_op98_store_state4);
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_176_2_reg_831 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_brmerge_fu_448_p2);
    sensitive << ( tmp_146_not_reg_817 );
    sensitive << ( icmp3_fu_402_p2 );

    SC_METHOD(thread_col_assign_1_t_fu_474_p2);
    sensitive << ( tmp_64_reg_864 );

    SC_METHOD(thread_col_buf_0_val_0_0_fu_491_p3);
    sensitive << ( brmerge_reg_869 );
    sensitive << ( k_buf_0_val_3_q0 );
    sensitive << ( tmp_49_fu_479_p5 );

    SC_METHOD(thread_col_buf_0_val_1_0_fu_510_p3);
    sensitive << ( brmerge_reg_869 );
    sensitive << ( k_buf_0_val_4_q0 );
    sensitive << ( tmp_50_fu_498_p5 );

    SC_METHOD(thread_col_buf_0_val_2_0_fu_529_p3);
    sensitive << ( brmerge_reg_869 );
    sensitive << ( k_buf_0_val_5_q0 );
    sensitive << ( tmp_51_fu_517_p5 );

    SC_METHOD(thread_exitcond460_i_i_fu_334_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_4_reg_245 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond461_i_i_fu_256_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_i_V_fu_262_p2);
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_icmp2_fu_356_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond460_i_i_fu_334_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_54_fu_346_p4 );

    SC_METHOD(thread_icmp3_fu_402_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond460_i_i_fu_334_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_62_fu_392_p4 );

    SC_METHOD(thread_icmp_fu_290_p2);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_280_p4 );

    SC_METHOD(thread_j_V_fu_340_p2);
    sensitive << ( t_V_4_reg_245 );

    SC_METHOD(thread_k_buf_0_val_3_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_41_fu_453_p1 );

    SC_METHOD(thread_k_buf_0_val_3_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_176_2_reg_831 );
    sensitive << ( k_buf_0_val_3_addr_reg_876 );

    SC_METHOD(thread_k_buf_0_val_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_3_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_176_2_reg_831 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_3_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_176_2_reg_831 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_4_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_41_fu_453_p1 );

    SC_METHOD(thread_k_buf_0_val_4_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( k_buf_0_val_4_addr_reg_882 );

    SC_METHOD(thread_k_buf_0_val_4_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_4_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_4_d1);
    sensitive << ( p_src_data_stream_V_dout );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( k_buf_0_val_3_q0 );
    sensitive << ( ap_condition_635 );

    SC_METHOD(thread_k_buf_0_val_4_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_5_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_41_fu_453_p1 );

    SC_METHOD(thread_k_buf_0_val_5_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( k_buf_0_val_5_addr_reg_888 );

    SC_METHOD(thread_k_buf_0_val_5_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_k_buf_0_val_5_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_k_buf_0_val_5_d1);
    sensitive << ( p_src_data_stream_V_dout );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( k_buf_0_val_4_q0 );
    sensitive << ( ap_condition_635 );

    SC_METHOD(thread_k_buf_0_val_5_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );
    sensitive << ( tmp_39_reg_827 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_not_s_fu_422_p2);
    sensitive << ( tmp_63_fu_414_p3 );

    SC_METHOD(thread_or_cond_i_i_fu_460_p2);
    sensitive << ( icmp_reg_822 );
    sensitive << ( icmp2_fu_356_p2 );

    SC_METHOD(thread_or_cond_i_i_i_fu_408_p2);
    sensitive << ( icmp3_fu_402_p2 );
    sensitive << ( rev_fu_386_p2 );

    SC_METHOD(thread_p_assign_1_cast_cast_fu_428_p3);
    sensitive << ( not_s_fu_422_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( col_buf_0_val_0_0_reg_898_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( temp_0_i_i_i_0210_i_6_fu_714_p3 );
    sensitive << ( tmp_222_2_2_fu_722_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_data_stream_V_blk_n);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( or_cond_i_i_i_reg_860 );
    sensitive << ( icmp_reg_822 );
    sensitive << ( tmp_s_reg_813 );

    SC_METHOD(thread_p_src_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op94_read_state4 );
    sensitive << ( ap_predicate_op102_read_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_rev_fu_386_p2);
    sensitive << ( tmp_56_fu_378_p3 );

    SC_METHOD(thread_row_assign_7_1_t_fu_318_p2);
    sensitive << ( tmp_53_fu_314_p1 );

    SC_METHOD(thread_row_assign_7_2_t_fu_324_p2);
    sensitive << ( tmp_53_fu_314_p1 );

    SC_METHOD(thread_src_kernel_win_0_va_8_fu_562_p3);
    sensitive << ( tmp_40_reg_835 );
    sensitive << ( col_buf_0_val_1_0_fu_510_p3 );
    sensitive << ( tmp_52_fu_551_p5 );

    SC_METHOD(thread_src_kernel_win_0_va_9_fu_580_p3);
    sensitive << ( tmp_40_reg_835 );
    sensitive << ( col_buf_0_val_2_0_fu_529_p3 );
    sensitive << ( tmp_57_fu_569_p5 );

    SC_METHOD(thread_t_V_4_cast_fu_330_p1);
    sensitive << ( t_V_4_reg_245 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_1_fu_613_p3);
    sensitive << ( src_kernel_win_0_va_9_fu_580_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_fu_599_p3 );
    sensitive << ( tmp_222_0_2_fu_607_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_2_fu_645_p3);
    sensitive << ( temp_0_i_i_i_0210_i_1_reg_912 );
    sensitive << ( src_kernel_win_0_va_3_fu_132 );
    sensitive << ( tmp_222_1_fu_640_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_3_fu_658_p3);
    sensitive << ( src_kernel_win_0_va_2_fu_128 );
    sensitive << ( temp_0_i_i_i_0210_i_2_fu_645_p3 );
    sensitive << ( tmp_222_1_1_fu_652_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_4_fu_671_p3);
    sensitive << ( src_kernel_win_0_va_8_reg_905 );
    sensitive << ( temp_0_i_i_i_0210_i_3_fu_658_p3 );
    sensitive << ( tmp_222_1_2_fu_666_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_5_fu_701_p3);
    sensitive << ( temp_0_i_i_i_0210_i_4_reg_918 );
    sensitive << ( src_kernel_win_0_va_1_fu_124 );
    sensitive << ( tmp_222_2_fu_696_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_6_fu_714_p3);
    sensitive << ( src_kernel_win_0_va_fu_120 );
    sensitive << ( temp_0_i_i_i_0210_i_5_fu_701_p3 );
    sensitive << ( tmp_222_2_1_fu_708_p2 );

    SC_METHOD(thread_temp_0_i_i_i_0210_i_fu_599_p3);
    sensitive << ( src_kernel_win_0_va_4_fu_136 );
    sensitive << ( src_kernel_win_0_va_5_fu_140 );
    sensitive << ( tmp_222_0_1_fu_593_p2 );

    SC_METHOD(thread_tmp_146_not_fu_274_p2);
    sensitive << ( tmp_s_fu_268_p2 );

    SC_METHOD(thread_tmp_176_2_fu_302_p2);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_tmp_222_0_1_fu_593_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_894 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_4_fu_136 );
    sensitive << ( src_kernel_win_0_va_5_fu_140 );

    SC_METHOD(thread_tmp_222_0_2_fu_607_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( or_cond_i_i_reg_894 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_9_fu_580_p3 );
    sensitive << ( temp_0_i_i_i_0210_i_fu_599_p3 );

    SC_METHOD(thread_tmp_222_1_1_fu_652_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( src_kernel_win_0_va_2_fu_128 );
    sensitive << ( temp_0_i_i_i_0210_i_2_fu_645_p3 );

    SC_METHOD(thread_tmp_222_1_2_fu_666_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter1_reg );
    sensitive << ( src_kernel_win_0_va_8_reg_905 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( temp_0_i_i_i_0210_i_3_fu_658_p3 );

    SC_METHOD(thread_tmp_222_1_fu_640_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter1_reg );
    sensitive << ( temp_0_i_i_i_0210_i_1_reg_912 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( src_kernel_win_0_va_3_fu_132 );

    SC_METHOD(thread_tmp_222_2_1_fu_708_p2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( src_kernel_win_0_va_fu_120 );
    sensitive << ( temp_0_i_i_i_0210_i_5_fu_701_p3 );

    SC_METHOD(thread_tmp_222_2_2_fu_722_p2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( col_buf_0_val_0_0_reg_898_pp0_iter2_reg );
    sensitive << ( temp_0_i_i_i_0210_i_6_fu_714_p3 );

    SC_METHOD(thread_tmp_222_2_fu_696_p2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( or_cond_i_i_reg_894_pp0_iter2_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( temp_0_i_i_i_0210_i_4_reg_918 );
    sensitive << ( src_kernel_win_0_va_1_fu_124 );

    SC_METHOD(thread_tmp_39_fu_296_p2);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_tmp_40_fu_308_p2);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_tmp_41_fu_453_p1);
    sensitive << ( x_fu_436_p3 );

    SC_METHOD(thread_tmp_53_fu_314_p1);
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_tmp_54_fu_346_p4);
    sensitive << ( t_V_4_reg_245 );

    SC_METHOD(thread_tmp_55_fu_362_p1);
    sensitive << ( t_V_4_reg_245 );

    SC_METHOD(thread_tmp_56_fu_378_p3);
    sensitive << ( ImagLoc_x_fu_366_p2 );

    SC_METHOD(thread_tmp_62_fu_392_p4);
    sensitive << ( ImagLoc_x_fu_366_p2 );

    SC_METHOD(thread_tmp_63_fu_414_p3);
    sensitive << ( ImagLoc_x_fu_366_p2 );

    SC_METHOD(thread_tmp_64_fu_444_p1);
    sensitive << ( x_fu_436_p3 );

    SC_METHOD(thread_tmp_fu_280_p4);
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_tmp_s_fu_268_p2);
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_234 );

    SC_METHOD(thread_x_fu_436_p3);
    sensitive << ( or_cond_i_i_i_fu_408_p2 );
    sensitive << ( ImagLoc_x_cast_fu_372_p2 );
    sensitive << ( p_assign_1_cast_cast_fu_428_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( exitcond461_i_i_fu_256_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond460_i_i_fu_334_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Dilate_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_data_stream_V_dout, "(port)p_src_data_stream_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_V_empty_n, "(port)p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_V_read, "(port)p_src_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_data_stream_V_blk_n, "p_src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, or_cond_i_i_i_reg_860, "or_cond_i_i_i_reg_860");
    sc_trace(mVcdFile, icmp_reg_822, "icmp_reg_822");
    sc_trace(mVcdFile, tmp_s_reg_813, "tmp_s_reg_813");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, or_cond_i_i_reg_894, "or_cond_i_i_reg_894");
    sc_trace(mVcdFile, or_cond_i_i_reg_894_pp0_iter2_reg, "or_cond_i_i_reg_894_pp0_iter2_reg");
    sc_trace(mVcdFile, t_V_4_reg_245, "t_V_4_reg_245");
    sc_trace(mVcdFile, exitcond461_i_i_fu_256_p2, "exitcond461_i_i_fu_256_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_V_fu_262_p2, "i_V_fu_262_p2");
    sc_trace(mVcdFile, i_V_reg_808, "i_V_reg_808");
    sc_trace(mVcdFile, tmp_s_fu_268_p2, "tmp_s_fu_268_p2");
    sc_trace(mVcdFile, tmp_146_not_fu_274_p2, "tmp_146_not_fu_274_p2");
    sc_trace(mVcdFile, tmp_146_not_reg_817, "tmp_146_not_reg_817");
    sc_trace(mVcdFile, icmp_fu_290_p2, "icmp_fu_290_p2");
    sc_trace(mVcdFile, tmp_39_fu_296_p2, "tmp_39_fu_296_p2");
    sc_trace(mVcdFile, tmp_39_reg_827, "tmp_39_reg_827");
    sc_trace(mVcdFile, tmp_176_2_fu_302_p2, "tmp_176_2_fu_302_p2");
    sc_trace(mVcdFile, tmp_176_2_reg_831, "tmp_176_2_reg_831");
    sc_trace(mVcdFile, tmp_40_fu_308_p2, "tmp_40_fu_308_p2");
    sc_trace(mVcdFile, tmp_40_reg_835, "tmp_40_reg_835");
    sc_trace(mVcdFile, row_assign_7_1_t_fu_318_p2, "row_assign_7_1_t_fu_318_p2");
    sc_trace(mVcdFile, row_assign_7_1_t_reg_841, "row_assign_7_1_t_reg_841");
    sc_trace(mVcdFile, row_assign_7_2_t_fu_324_p2, "row_assign_7_2_t_fu_324_p2");
    sc_trace(mVcdFile, row_assign_7_2_t_reg_846, "row_assign_7_2_t_reg_846");
    sc_trace(mVcdFile, exitcond460_i_i_fu_334_p2, "exitcond460_i_i_fu_334_p2");
    sc_trace(mVcdFile, exitcond460_i_i_reg_851, "exitcond460_i_i_reg_851");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op94_read_state4, "ap_predicate_op94_read_state4");
    sc_trace(mVcdFile, ap_predicate_op102_read_state4, "ap_predicate_op102_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond460_i_i_reg_851_pp0_iter1_reg, "exitcond460_i_i_reg_851_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond460_i_i_reg_851_pp0_iter2_reg, "exitcond460_i_i_reg_851_pp0_iter2_reg");
    sc_trace(mVcdFile, j_V_fu_340_p2, "j_V_fu_340_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, or_cond_i_i_i_fu_408_p2, "or_cond_i_i_i_fu_408_p2");
    sc_trace(mVcdFile, tmp_64_fu_444_p1, "tmp_64_fu_444_p1");
    sc_trace(mVcdFile, tmp_64_reg_864, "tmp_64_reg_864");
    sc_trace(mVcdFile, brmerge_fu_448_p2, "brmerge_fu_448_p2");
    sc_trace(mVcdFile, brmerge_reg_869, "brmerge_reg_869");
    sc_trace(mVcdFile, k_buf_0_val_3_addr_reg_876, "k_buf_0_val_3_addr_reg_876");
    sc_trace(mVcdFile, k_buf_0_val_4_addr_reg_882, "k_buf_0_val_4_addr_reg_882");
    sc_trace(mVcdFile, k_buf_0_val_5_addr_reg_888, "k_buf_0_val_5_addr_reg_888");
    sc_trace(mVcdFile, or_cond_i_i_fu_460_p2, "or_cond_i_i_fu_460_p2");
    sc_trace(mVcdFile, or_cond_i_i_reg_894_pp0_iter1_reg, "or_cond_i_i_reg_894_pp0_iter1_reg");
    sc_trace(mVcdFile, col_buf_0_val_0_0_fu_491_p3, "col_buf_0_val_0_0_fu_491_p3");
    sc_trace(mVcdFile, col_buf_0_val_0_0_reg_898, "col_buf_0_val_0_0_reg_898");
    sc_trace(mVcdFile, col_buf_0_val_0_0_reg_898_pp0_iter2_reg, "col_buf_0_val_0_0_reg_898_pp0_iter2_reg");
    sc_trace(mVcdFile, src_kernel_win_0_va_8_fu_562_p3, "src_kernel_win_0_va_8_fu_562_p3");
    sc_trace(mVcdFile, src_kernel_win_0_va_8_reg_905, "src_kernel_win_0_va_8_reg_905");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_1_fu_613_p3, "temp_0_i_i_i_0210_i_1_fu_613_p3");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_1_reg_912, "temp_0_i_i_i_0210_i_1_reg_912");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_4_fu_671_p3, "temp_0_i_i_i_0210_i_4_fu_671_p3");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_4_reg_918, "temp_0_i_i_i_0210_i_4_reg_918");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, k_buf_0_val_3_address0, "k_buf_0_val_3_address0");
    sc_trace(mVcdFile, k_buf_0_val_3_ce0, "k_buf_0_val_3_ce0");
    sc_trace(mVcdFile, k_buf_0_val_3_q0, "k_buf_0_val_3_q0");
    sc_trace(mVcdFile, k_buf_0_val_3_address1, "k_buf_0_val_3_address1");
    sc_trace(mVcdFile, k_buf_0_val_3_ce1, "k_buf_0_val_3_ce1");
    sc_trace(mVcdFile, k_buf_0_val_3_we1, "k_buf_0_val_3_we1");
    sc_trace(mVcdFile, k_buf_0_val_4_address0, "k_buf_0_val_4_address0");
    sc_trace(mVcdFile, k_buf_0_val_4_ce0, "k_buf_0_val_4_ce0");
    sc_trace(mVcdFile, k_buf_0_val_4_q0, "k_buf_0_val_4_q0");
    sc_trace(mVcdFile, k_buf_0_val_4_address1, "k_buf_0_val_4_address1");
    sc_trace(mVcdFile, k_buf_0_val_4_ce1, "k_buf_0_val_4_ce1");
    sc_trace(mVcdFile, k_buf_0_val_4_we1, "k_buf_0_val_4_we1");
    sc_trace(mVcdFile, k_buf_0_val_4_d1, "k_buf_0_val_4_d1");
    sc_trace(mVcdFile, k_buf_0_val_5_address0, "k_buf_0_val_5_address0");
    sc_trace(mVcdFile, k_buf_0_val_5_ce0, "k_buf_0_val_5_ce0");
    sc_trace(mVcdFile, k_buf_0_val_5_q0, "k_buf_0_val_5_q0");
    sc_trace(mVcdFile, k_buf_0_val_5_address1, "k_buf_0_val_5_address1");
    sc_trace(mVcdFile, k_buf_0_val_5_ce1, "k_buf_0_val_5_ce1");
    sc_trace(mVcdFile, k_buf_0_val_5_we1, "k_buf_0_val_5_we1");
    sc_trace(mVcdFile, k_buf_0_val_5_d1, "k_buf_0_val_5_d1");
    sc_trace(mVcdFile, t_V_reg_234, "t_V_reg_234");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_41_fu_453_p1, "tmp_41_fu_453_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, src_kernel_win_0_va_fu_120, "src_kernel_win_0_va_fu_120");
    sc_trace(mVcdFile, src_kernel_win_0_va_1_fu_124, "src_kernel_win_0_va_1_fu_124");
    sc_trace(mVcdFile, src_kernel_win_0_va_2_fu_128, "src_kernel_win_0_va_2_fu_128");
    sc_trace(mVcdFile, src_kernel_win_0_va_3_fu_132, "src_kernel_win_0_va_3_fu_132");
    sc_trace(mVcdFile, src_kernel_win_0_va_4_fu_136, "src_kernel_win_0_va_4_fu_136");
    sc_trace(mVcdFile, src_kernel_win_0_va_9_fu_580_p3, "src_kernel_win_0_va_9_fu_580_p3");
    sc_trace(mVcdFile, src_kernel_win_0_va_5_fu_140, "src_kernel_win_0_va_5_fu_140");
    sc_trace(mVcdFile, src_kernel_win_0_va_6_fu_144, "src_kernel_win_0_va_6_fu_144");
    sc_trace(mVcdFile, right_border_buf_0_s_fu_148, "right_border_buf_0_s_fu_148");
    sc_trace(mVcdFile, col_buf_0_val_2_0_fu_529_p3, "col_buf_0_val_2_0_fu_529_p3");
    sc_trace(mVcdFile, right_border_buf_0_1_fu_152, "right_border_buf_0_1_fu_152");
    sc_trace(mVcdFile, col_buf_0_val_1_0_fu_510_p3, "col_buf_0_val_1_0_fu_510_p3");
    sc_trace(mVcdFile, tmp_fu_280_p4, "tmp_fu_280_p4");
    sc_trace(mVcdFile, tmp_53_fu_314_p1, "tmp_53_fu_314_p1");
    sc_trace(mVcdFile, tmp_54_fu_346_p4, "tmp_54_fu_346_p4");
    sc_trace(mVcdFile, t_V_4_cast_fu_330_p1, "t_V_4_cast_fu_330_p1");
    sc_trace(mVcdFile, tmp_55_fu_362_p1, "tmp_55_fu_362_p1");
    sc_trace(mVcdFile, ImagLoc_x_fu_366_p2, "ImagLoc_x_fu_366_p2");
    sc_trace(mVcdFile, tmp_56_fu_378_p3, "tmp_56_fu_378_p3");
    sc_trace(mVcdFile, tmp_62_fu_392_p4, "tmp_62_fu_392_p4");
    sc_trace(mVcdFile, icmp3_fu_402_p2, "icmp3_fu_402_p2");
    sc_trace(mVcdFile, rev_fu_386_p2, "rev_fu_386_p2");
    sc_trace(mVcdFile, tmp_63_fu_414_p3, "tmp_63_fu_414_p3");
    sc_trace(mVcdFile, not_s_fu_422_p2, "not_s_fu_422_p2");
    sc_trace(mVcdFile, ImagLoc_x_cast_fu_372_p2, "ImagLoc_x_cast_fu_372_p2");
    sc_trace(mVcdFile, p_assign_1_cast_cast_fu_428_p3, "p_assign_1_cast_cast_fu_428_p3");
    sc_trace(mVcdFile, x_fu_436_p3, "x_fu_436_p3");
    sc_trace(mVcdFile, icmp2_fu_356_p2, "icmp2_fu_356_p2");
    sc_trace(mVcdFile, col_assign_1_t_fu_474_p2, "col_assign_1_t_fu_474_p2");
    sc_trace(mVcdFile, tmp_49_fu_479_p5, "tmp_49_fu_479_p5");
    sc_trace(mVcdFile, tmp_50_fu_498_p5, "tmp_50_fu_498_p5");
    sc_trace(mVcdFile, tmp_51_fu_517_p5, "tmp_51_fu_517_p5");
    sc_trace(mVcdFile, tmp_52_fu_551_p5, "tmp_52_fu_551_p5");
    sc_trace(mVcdFile, tmp_57_fu_569_p5, "tmp_57_fu_569_p5");
    sc_trace(mVcdFile, tmp_222_0_1_fu_593_p2, "tmp_222_0_1_fu_593_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_fu_599_p3, "temp_0_i_i_i_0210_i_fu_599_p3");
    sc_trace(mVcdFile, tmp_222_0_2_fu_607_p2, "tmp_222_0_2_fu_607_p2");
    sc_trace(mVcdFile, tmp_222_1_fu_640_p2, "tmp_222_1_fu_640_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_2_fu_645_p3, "temp_0_i_i_i_0210_i_2_fu_645_p3");
    sc_trace(mVcdFile, tmp_222_1_1_fu_652_p2, "tmp_222_1_1_fu_652_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_3_fu_658_p3, "temp_0_i_i_i_0210_i_3_fu_658_p3");
    sc_trace(mVcdFile, tmp_222_1_2_fu_666_p2, "tmp_222_1_2_fu_666_p2");
    sc_trace(mVcdFile, tmp_222_2_fu_696_p2, "tmp_222_2_fu_696_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_5_fu_701_p3, "temp_0_i_i_i_0210_i_5_fu_701_p3");
    sc_trace(mVcdFile, tmp_222_2_1_fu_708_p2, "tmp_222_2_1_fu_708_p2");
    sc_trace(mVcdFile, temp_0_i_i_i_0210_i_6_fu_714_p3, "temp_0_i_i_i_0210_i_6_fu_714_p3");
    sc_trace(mVcdFile, tmp_222_2_2_fu_722_p2, "tmp_222_2_2_fu_722_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0, "ap_block_pp0");
    sc_trace(mVcdFile, ap_enable_operation_68, "ap_enable_operation_68");
    sc_trace(mVcdFile, ap_enable_state3_pp0_iter0_stage0, "ap_enable_state3_pp0_iter0_stage0");
    sc_trace(mVcdFile, ap_enable_operation_84, "ap_enable_operation_84");
    sc_trace(mVcdFile, ap_enable_state4_pp0_iter1_stage0, "ap_enable_state4_pp0_iter1_stage0");
    sc_trace(mVcdFile, ap_predicate_op98_store_state4, "ap_predicate_op98_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_98, "ap_enable_operation_98");
    sc_trace(mVcdFile, ap_predicate_op103_store_state4, "ap_predicate_op103_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_103, "ap_enable_operation_103");
    sc_trace(mVcdFile, ap_enable_operation_70, "ap_enable_operation_70");
    sc_trace(mVcdFile, ap_enable_operation_88, "ap_enable_operation_88");
    sc_trace(mVcdFile, ap_predicate_op96_store_state4, "ap_predicate_op96_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_96, "ap_enable_operation_96");
    sc_trace(mVcdFile, ap_predicate_op101_store_state4, "ap_predicate_op101_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_101, "ap_enable_operation_101");
    sc_trace(mVcdFile, ap_enable_operation_72, "ap_enable_operation_72");
    sc_trace(mVcdFile, ap_enable_operation_91, "ap_enable_operation_91");
    sc_trace(mVcdFile, ap_predicate_op95_store_state4, "ap_predicate_op95_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_95, "ap_enable_operation_95");
    sc_trace(mVcdFile, ap_predicate_op100_store_state4, "ap_predicate_op100_store_state4");
    sc_trace(mVcdFile, ap_enable_operation_100, "ap_enable_operation_100");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_635, "ap_condition_635");
#endif

    }
}

Dilate::~Dilate() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete k_buf_0_val_3_U;
    delete k_buf_0_val_4_U;
    delete k_buf_0_val_5_U;
    delete doCorner_mux_32_8ocq_U31;
    delete doCorner_mux_32_8ocq_U32;
    delete doCorner_mux_32_8ocq_U33;
    delete doCorner_mux_32_8ocq_U34;
    delete doCorner_mux_32_8ocq_U35;
}

void Dilate::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv8_0;
}

void Dilate::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_256_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_256_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_256_p2.read()))) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_334_p2.read()))) {
        t_V_4_reg_245 = j_V_fu_340_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_256_p2.read()))) {
        t_V_4_reg_245 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        t_V_reg_234 = i_V_reg_808.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        t_V_reg_234 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_334_p2.read()))) {
        brmerge_reg_869 = brmerge_fu_448_p2.read();
        k_buf_0_val_3_addr_reg_876 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
        k_buf_0_val_4_addr_reg_882 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
        k_buf_0_val_5_addr_reg_888 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
        or_cond_i_i_i_reg_860 = or_cond_i_i_i_fu_408_p2.read();
        or_cond_i_i_reg_894 = or_cond_i_i_fu_460_p2.read();
        tmp_64_reg_864 = tmp_64_fu_444_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        col_buf_0_val_0_0_reg_898 = col_buf_0_val_0_0_fu_491_p3.read();
        exitcond460_i_i_reg_851 = exitcond460_i_i_fu_334_p2.read();
        exitcond460_i_i_reg_851_pp0_iter1_reg = exitcond460_i_i_reg_851.read();
        or_cond_i_i_reg_894_pp0_iter1_reg = or_cond_i_i_reg_894.read();
        src_kernel_win_0_va_8_reg_905 = src_kernel_win_0_va_8_fu_562_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        col_buf_0_val_0_0_reg_898_pp0_iter2_reg = col_buf_0_val_0_0_reg_898.read();
        exitcond460_i_i_reg_851_pp0_iter2_reg = exitcond460_i_i_reg_851_pp0_iter1_reg.read();
        or_cond_i_i_reg_894_pp0_iter2_reg = or_cond_i_i_reg_894_pp0_iter1_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_V_reg_808 = i_V_fu_262_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond461_i_i_fu_256_p2.read()))) {
        icmp_reg_822 = icmp_fu_290_p2.read();
        row_assign_7_1_t_reg_841 = row_assign_7_1_t_fu_318_p2.read();
        row_assign_7_2_t_reg_846 = row_assign_7_2_t_fu_324_p2.read();
        tmp_146_not_reg_817 = tmp_146_not_fu_274_p2.read();
        tmp_176_2_reg_831 = tmp_176_2_fu_302_p2.read();
        tmp_39_reg_827 = tmp_39_fu_296_p2.read();
        tmp_40_reg_835 = tmp_40_fu_308_p2.read();
        tmp_s_reg_813 = tmp_s_fu_268_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        right_border_buf_0_1_fu_152 = col_buf_0_val_1_0_fu_510_p3.read();
        right_border_buf_0_s_fu_148 = col_buf_0_val_2_0_fu_529_p3.read();
        src_kernel_win_0_va_6_fu_144 = col_buf_0_val_0_0_fu_491_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_reg_851_pp0_iter2_reg.read()))) {
        src_kernel_win_0_va_1_fu_124 = src_kernel_win_0_va_fu_120.read();
        src_kernel_win_0_va_fu_120 = col_buf_0_val_0_0_reg_898_pp0_iter2_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_reg_851_pp0_iter1_reg.read()))) {
        src_kernel_win_0_va_2_fu_128 = src_kernel_win_0_va_8_reg_905.read();
        src_kernel_win_0_va_3_fu_132 = src_kernel_win_0_va_2_fu_128.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_reg_851.read()))) {
        src_kernel_win_0_va_4_fu_136 = src_kernel_win_0_va_9_fu_580_p3.read();
        src_kernel_win_0_va_5_fu_140 = src_kernel_win_0_va_4_fu_136.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894.read()))) {
        temp_0_i_i_i_0210_i_1_reg_912 = temp_0_i_i_i_0210_i_1_fu_613_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter1_reg.read()))) {
        temp_0_i_i_i_0210_i_4_reg_918 = temp_0_i_i_i_0210_i_4_fu_671_p3.read();
    }
}

void Dilate::thread_ImagLoc_x_cast_fu_372_p2() {
    ImagLoc_x_cast_fu_372_p2 = (!ap_const_lv10_3FF.is_01() || !tmp_55_fu_362_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3FF) + sc_biguint<10>(tmp_55_fu_362_p1.read()));
}

void Dilate::thread_ImagLoc_x_fu_366_p2() {
    ImagLoc_x_fu_366_p2 = (!ap_const_lv12_FFF.is_01() || !t_V_4_cast_fu_330_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FFF) + sc_biguint<12>(t_V_4_cast_fu_330_p1.read()));
}

void Dilate::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void Dilate::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Dilate::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Dilate::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[3];
}

void Dilate::thread_ap_block_pp0() {
    ap_block_pp0 = (esl_seteq<1,4,4>(ap_ST_fsm_pp0_stage0, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_pp0_stage0_subdone.read()));
}

void Dilate::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op94_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op102_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op94_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op102_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op94_read_state4.read())) || 
   (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op102_read_state4.read())))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void Dilate::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Dilate::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = ((esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op94_read_state4.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op102_read_state4.read())));
}

void Dilate::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = (esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read()));
}

void Dilate::thread_ap_condition_635() {
    ap_condition_635 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1));
}

void Dilate::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_334_p2.read())) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void Dilate::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_256_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Dilate::thread_ap_enable_operation_100() {
    ap_enable_operation_100 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op100_store_state4.read());
}

void Dilate::thread_ap_enable_operation_101() {
    ap_enable_operation_101 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op101_store_state4.read());
}

void Dilate::thread_ap_enable_operation_103() {
    ap_enable_operation_103 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op103_store_state4.read());
}

void Dilate::thread_ap_enable_operation_68() {
    ap_enable_operation_68 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_334_p2.read());
}

void Dilate::thread_ap_enable_operation_70() {
    ap_enable_operation_70 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_334_p2.read());
}

void Dilate::thread_ap_enable_operation_72() {
    ap_enable_operation_72 = esl_seteq<1,1,1>(ap_const_lv1_0, exitcond460_i_i_fu_334_p2.read());
}

void Dilate::thread_ap_enable_operation_84() {
    ap_enable_operation_84 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_88() {
    ap_enable_operation_88 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_91() {
    ap_enable_operation_91 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Dilate::thread_ap_enable_operation_95() {
    ap_enable_operation_95 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op95_store_state4.read());
}

void Dilate::thread_ap_enable_operation_96() {
    ap_enable_operation_96 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op96_store_state4.read());
}

void Dilate::thread_ap_enable_operation_98() {
    ap_enable_operation_98 = esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op98_store_state4.read());
}

void Dilate::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Dilate::thread_ap_enable_state3_pp0_iter0_stage0() {
    ap_enable_state3_pp0_iter0_stage0 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1));
}

void Dilate::thread_ap_enable_state4_pp0_iter1_stage0() {
    ap_enable_state4_pp0_iter1_stage0 = (esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_1));
}

void Dilate::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Dilate::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Dilate::thread_ap_predicate_op100_store_state4() {
    ap_predicate_op100_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()));
}

void Dilate::thread_ap_predicate_op101_store_state4() {
    ap_predicate_op101_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()));
}

void Dilate::thread_ap_predicate_op102_read_state4() {
    ap_predicate_op102_read_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()));
}

void Dilate::thread_ap_predicate_op103_store_state4() {
    ap_predicate_op103_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()));
}

void Dilate::thread_ap_predicate_op94_read_state4() {
    ap_predicate_op94_read_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0));
}

void Dilate::thread_ap_predicate_op95_store_state4() {
    ap_predicate_op95_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read()));
}

void Dilate::thread_ap_predicate_op96_store_state4() {
    ap_predicate_op96_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read()));
}

void Dilate::thread_ap_predicate_op98_store_state4() {
    ap_predicate_op98_store_state4 = (esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_176_2_reg_831.read()));
}

void Dilate::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_256_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Dilate::thread_brmerge_fu_448_p2() {
    brmerge_fu_448_p2 = (icmp3_fu_402_p2.read() | tmp_146_not_reg_817.read());
}

void Dilate::thread_col_assign_1_t_fu_474_p2() {
    col_assign_1_t_fu_474_p2 = (tmp_64_reg_864.read() ^ ap_const_lv2_3);
}

void Dilate::thread_col_buf_0_val_0_0_fu_491_p3() {
    col_buf_0_val_0_0_fu_491_p3 = (!brmerge_reg_869.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_869.read()[0].to_bool())? k_buf_0_val_3_q0.read(): tmp_49_fu_479_p5.read());
}

void Dilate::thread_col_buf_0_val_1_0_fu_510_p3() {
    col_buf_0_val_1_0_fu_510_p3 = (!brmerge_reg_869.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_869.read()[0].to_bool())? k_buf_0_val_4_q0.read(): tmp_50_fu_498_p5.read());
}

void Dilate::thread_col_buf_0_val_2_0_fu_529_p3() {
    col_buf_0_val_2_0_fu_529_p3 = (!brmerge_reg_869.read()[0].is_01())? sc_lv<8>(): ((brmerge_reg_869.read()[0].to_bool())? k_buf_0_val_5_q0.read(): tmp_51_fu_517_p5.read());
}

void Dilate::thread_exitcond460_i_i_fu_334_p2() {
    exitcond460_i_i_fu_334_p2 = (!t_V_4_reg_245.read().is_01() || !ap_const_lv11_402.is_01())? sc_lv<1>(): sc_lv<1>(t_V_4_reg_245.read() == ap_const_lv11_402);
}

void Dilate::thread_exitcond461_i_i_fu_256_p2() {
    exitcond461_i_i_fu_256_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_302.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_234.read() == ap_const_lv10_302);
}

void Dilate::thread_i_V_fu_262_p2() {
    i_V_fu_262_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(t_V_reg_234.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void Dilate::thread_icmp2_fu_356_p2() {
    icmp2_fu_356_p2 = (!tmp_54_fu_346_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_54_fu_346_p4.read() != ap_const_lv10_0);
}

void Dilate::thread_icmp3_fu_402_p2() {
    icmp3_fu_402_p2 = (!tmp_62_fu_392_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_62_fu_392_p4.read() != ap_const_lv2_1);
}

void Dilate::thread_icmp_fu_290_p2() {
    icmp_fu_290_p2 = (!tmp_fu_280_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_280_p4.read() != ap_const_lv9_0);
}

void Dilate::thread_j_V_fu_340_p2() {
    j_V_fu_340_p2 = (!t_V_4_reg_245.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(t_V_4_reg_245.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void Dilate::thread_k_buf_0_val_3_address0() {
    k_buf_0_val_3_address0 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
}

void Dilate::thread_k_buf_0_val_3_address1() {
    k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_876.read();
}

void Dilate::thread_k_buf_0_val_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_3_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_3_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_176_2_reg_831.read())))) {
        k_buf_0_val_3_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_3_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_176_2_reg_831.read())))) {
        k_buf_0_val_3_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_3_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_address0() {
    k_buf_0_val_4_address0 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
}

void Dilate::thread_k_buf_0_val_4_address1() {
    k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_882.read();
}

void Dilate::thread_k_buf_0_val_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_4_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read())))) {
        k_buf_0_val_4_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_4_d1() {
    if (esl_seteq<1,1,1>(ap_condition_635.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()))) {
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0.read();
        } else if ((esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read()))) {
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout.read();
        } else {
            k_buf_0_val_4_d1 = "XXXXXXXX";
        }
    } else {
        k_buf_0_val_4_d1 = "XXXXXXXX";
    }
}

void Dilate::thread_k_buf_0_val_4_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read())))) {
        k_buf_0_val_4_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_4_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_address0() {
    k_buf_0_val_5_address0 =  (sc_lv<10>) (tmp_41_fu_453_p1.read());
}

void Dilate::thread_k_buf_0_val_5_address1() {
    k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_888.read();
}

void Dilate::thread_k_buf_0_val_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        k_buf_0_val_5_ce0 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_ce0 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read())))) {
        k_buf_0_val_5_ce1 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_ce1 = ap_const_logic_0;
    }
}

void Dilate::thread_k_buf_0_val_5_d1() {
    if (esl_seteq<1,1,1>(ap_condition_635.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()))) {
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0.read();
        } else if ((esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read()))) {
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout.read();
        } else {
            k_buf_0_val_5_d1 = "XXXXXXXX";
        }
    } else {
        k_buf_0_val_5_d1 = "XXXXXXXX";
    }
}

void Dilate::thread_k_buf_0_val_5_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_827.read())))) {
        k_buf_0_val_5_we1 = ap_const_logic_1;
    } else {
        k_buf_0_val_5_we1 = ap_const_logic_0;
    }
}

void Dilate::thread_not_s_fu_422_p2() {
    not_s_fu_422_p2 = (tmp_63_fu_414_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_or_cond_i_i_fu_460_p2() {
    or_cond_i_i_fu_460_p2 = (icmp_reg_822.read() & icmp2_fu_356_p2.read());
}

void Dilate::thread_or_cond_i_i_i_fu_408_p2() {
    or_cond_i_i_i_fu_408_p2 = (icmp3_fu_402_p2.read() & rev_fu_386_p2.read());
}

void Dilate::thread_p_assign_1_cast_cast_fu_428_p3() {
    p_assign_1_cast_cast_fu_428_p3 = (!not_s_fu_422_p2.read()[0].is_01())? sc_lv<10>(): ((not_s_fu_422_p2.read()[0].to_bool())? ap_const_lv10_3FF: ap_const_lv10_0);
}

void Dilate::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void Dilate::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!tmp_222_2_2_fu_722_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_2_2_fu_722_p2.read()[0].to_bool())? col_buf_0_val_0_0_reg_898_pp0_iter2_reg.read(): temp_0_i_i_i_0210_i_6_fu_714_p3.read());
}

void Dilate::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_i_reg_894_pp0_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void Dilate::thread_p_src_data_stream_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_reg_822.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(or_cond_i_i_i_reg_860.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_reg_822.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_s_reg_813.read())))) {
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n.read();
    } else {
        p_src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void Dilate::thread_p_src_data_stream_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op94_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op102_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        p_src_data_stream_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_V_read = ap_const_logic_0;
    }
}

void Dilate::thread_rev_fu_386_p2() {
    rev_fu_386_p2 = (tmp_56_fu_378_p3.read() ^ ap_const_lv1_1);
}

void Dilate::thread_row_assign_7_1_t_fu_318_p2() {
    row_assign_7_1_t_fu_318_p2 = (tmp_53_fu_314_p1.read() ^ ap_const_lv2_1);
}

void Dilate::thread_row_assign_7_2_t_fu_324_p2() {
    row_assign_7_2_t_fu_324_p2 = (!ap_const_lv2_2.is_01() || !tmp_53_fu_314_p1.read().is_01())? sc_lv<2>(): (sc_bigint<2>(ap_const_lv2_2) - sc_biguint<2>(tmp_53_fu_314_p1.read()));
}

void Dilate::thread_src_kernel_win_0_va_8_fu_562_p3() {
    src_kernel_win_0_va_8_fu_562_p3 = (!tmp_40_reg_835.read()[0].is_01())? sc_lv<8>(): ((tmp_40_reg_835.read()[0].to_bool())? tmp_52_fu_551_p5.read(): col_buf_0_val_1_0_fu_510_p3.read());
}

void Dilate::thread_src_kernel_win_0_va_9_fu_580_p3() {
    src_kernel_win_0_va_9_fu_580_p3 = (!tmp_40_reg_835.read()[0].is_01())? sc_lv<8>(): ((tmp_40_reg_835.read()[0].to_bool())? tmp_57_fu_569_p5.read(): col_buf_0_val_2_0_fu_529_p3.read());
}

void Dilate::thread_t_V_4_cast_fu_330_p1() {
    t_V_4_cast_fu_330_p1 = esl_zext<12,11>(t_V_4_reg_245.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_1_fu_613_p3() {
    temp_0_i_i_i_0210_i_1_fu_613_p3 = (!tmp_222_0_2_fu_607_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_0_2_fu_607_p2.read()[0].to_bool())? src_kernel_win_0_va_9_fu_580_p3.read(): temp_0_i_i_i_0210_i_fu_599_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_2_fu_645_p3() {
    temp_0_i_i_i_0210_i_2_fu_645_p3 = (!tmp_222_1_fu_640_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_1_fu_640_p2.read()[0].to_bool())? src_kernel_win_0_va_3_fu_132.read(): temp_0_i_i_i_0210_i_1_reg_912.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_3_fu_658_p3() {
    temp_0_i_i_i_0210_i_3_fu_658_p3 = (!tmp_222_1_1_fu_652_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_1_1_fu_652_p2.read()[0].to_bool())? src_kernel_win_0_va_2_fu_128.read(): temp_0_i_i_i_0210_i_2_fu_645_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_4_fu_671_p3() {
    temp_0_i_i_i_0210_i_4_fu_671_p3 = (!tmp_222_1_2_fu_666_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_1_2_fu_666_p2.read()[0].to_bool())? src_kernel_win_0_va_8_reg_905.read(): temp_0_i_i_i_0210_i_3_fu_658_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_5_fu_701_p3() {
    temp_0_i_i_i_0210_i_5_fu_701_p3 = (!tmp_222_2_fu_696_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_2_fu_696_p2.read()[0].to_bool())? src_kernel_win_0_va_1_fu_124.read(): temp_0_i_i_i_0210_i_4_reg_918.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_6_fu_714_p3() {
    temp_0_i_i_i_0210_i_6_fu_714_p3 = (!tmp_222_2_1_fu_708_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_2_1_fu_708_p2.read()[0].to_bool())? src_kernel_win_0_va_fu_120.read(): temp_0_i_i_i_0210_i_5_fu_701_p3.read());
}

void Dilate::thread_temp_0_i_i_i_0210_i_fu_599_p3() {
    temp_0_i_i_i_0210_i_fu_599_p3 = (!tmp_222_0_1_fu_593_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_222_0_1_fu_593_p2.read()[0].to_bool())? src_kernel_win_0_va_4_fu_136.read(): src_kernel_win_0_va_5_fu_140.read());
}

void Dilate::thread_tmp_146_not_fu_274_p2() {
    tmp_146_not_fu_274_p2 = (tmp_s_fu_268_p2.read() ^ ap_const_lv1_1);
}

void Dilate::thread_tmp_176_2_fu_302_p2() {
    tmp_176_2_fu_302_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_234.read() == ap_const_lv10_1);
}

void Dilate::thread_tmp_222_0_1_fu_593_p2() {
    tmp_222_0_1_fu_593_p2 = (!src_kernel_win_0_va_4_fu_136.read().is_01() || !src_kernel_win_0_va_5_fu_140.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_4_fu_136.read()) > sc_biguint<8>(src_kernel_win_0_va_5_fu_140.read()));
}

void Dilate::thread_tmp_222_0_2_fu_607_p2() {
    tmp_222_0_2_fu_607_p2 = (!src_kernel_win_0_va_9_fu_580_p3.read().is_01() || !temp_0_i_i_i_0210_i_fu_599_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_9_fu_580_p3.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_fu_599_p3.read()));
}

void Dilate::thread_tmp_222_1_1_fu_652_p2() {
    tmp_222_1_1_fu_652_p2 = (!src_kernel_win_0_va_2_fu_128.read().is_01() || !temp_0_i_i_i_0210_i_2_fu_645_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_2_fu_128.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_2_fu_645_p3.read()));
}

void Dilate::thread_tmp_222_1_2_fu_666_p2() {
    tmp_222_1_2_fu_666_p2 = (!src_kernel_win_0_va_8_reg_905.read().is_01() || !temp_0_i_i_i_0210_i_3_fu_658_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_8_reg_905.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_3_fu_658_p3.read()));
}

void Dilate::thread_tmp_222_1_fu_640_p2() {
    tmp_222_1_fu_640_p2 = (!src_kernel_win_0_va_3_fu_132.read().is_01() || !temp_0_i_i_i_0210_i_1_reg_912.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_3_fu_132.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_1_reg_912.read()));
}

void Dilate::thread_tmp_222_2_1_fu_708_p2() {
    tmp_222_2_1_fu_708_p2 = (!src_kernel_win_0_va_fu_120.read().is_01() || !temp_0_i_i_i_0210_i_5_fu_701_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_fu_120.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_5_fu_701_p3.read()));
}

void Dilate::thread_tmp_222_2_2_fu_722_p2() {
    tmp_222_2_2_fu_722_p2 = (!col_buf_0_val_0_0_reg_898_pp0_iter2_reg.read().is_01() || !temp_0_i_i_i_0210_i_6_fu_714_p3.read().is_01())? sc_lv<1>(): (sc_biguint<8>(col_buf_0_val_0_0_reg_898_pp0_iter2_reg.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_6_fu_714_p3.read()));
}

void Dilate::thread_tmp_222_2_fu_696_p2() {
    tmp_222_2_fu_696_p2 = (!src_kernel_win_0_va_1_fu_124.read().is_01() || !temp_0_i_i_i_0210_i_4_reg_918.read().is_01())? sc_lv<1>(): (sc_biguint<8>(src_kernel_win_0_va_1_fu_124.read()) > sc_biguint<8>(temp_0_i_i_i_0210_i_4_reg_918.read()));
}

void Dilate::thread_tmp_39_fu_296_p2() {
    tmp_39_fu_296_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_234.read() == ap_const_lv10_0);
}

void Dilate::thread_tmp_40_fu_308_p2() {
    tmp_40_fu_308_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_300.is_01())? sc_lv<1>(): (sc_biguint<10>(t_V_reg_234.read()) > sc_biguint<10>(ap_const_lv10_300));
}

void Dilate::thread_tmp_41_fu_453_p1() {
    tmp_41_fu_453_p1 = esl_zext<64,10>(x_fu_436_p3.read());
}

void Dilate::thread_tmp_53_fu_314_p1() {
    tmp_53_fu_314_p1 = t_V_reg_234.read().range(2-1, 0);
}

void Dilate::thread_tmp_54_fu_346_p4() {
    tmp_54_fu_346_p4 = t_V_4_reg_245.read().range(10, 1);
}

void Dilate::thread_tmp_55_fu_362_p1() {
    tmp_55_fu_362_p1 = t_V_4_reg_245.read().range(10-1, 0);
}

void Dilate::thread_tmp_56_fu_378_p3() {
    tmp_56_fu_378_p3 = ImagLoc_x_fu_366_p2.read().range(11, 11);
}

void Dilate::thread_tmp_62_fu_392_p4() {
    tmp_62_fu_392_p4 = ImagLoc_x_fu_366_p2.read().range(11, 10);
}

void Dilate::thread_tmp_63_fu_414_p3() {
    tmp_63_fu_414_p3 = ImagLoc_x_fu_366_p2.read().range(11, 11);
}

void Dilate::thread_tmp_64_fu_444_p1() {
    tmp_64_fu_444_p1 = x_fu_436_p3.read().range(2-1, 0);
}

void Dilate::thread_tmp_fu_280_p4() {
    tmp_fu_280_p4 = t_V_reg_234.read().range(9, 1);
}

void Dilate::thread_tmp_s_fu_268_p2() {
    tmp_s_fu_268_p2 = (!t_V_reg_234.read().is_01() || !ap_const_lv10_300.is_01())? sc_lv<1>(): (sc_biguint<10>(t_V_reg_234.read()) < sc_biguint<10>(ap_const_lv10_300));
}

void Dilate::thread_x_fu_436_p3() {
    x_fu_436_p3 = (!or_cond_i_i_i_fu_408_p2.read()[0].is_01())? sc_lv<10>(): ((or_cond_i_i_i_fu_408_p2.read()[0].to_bool())? ImagLoc_x_cast_fu_372_p2.read(): p_assign_1_cast_cast_fu_428_p3.read());
}

void Dilate::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond461_i_i_fu_256_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_334_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, exitcond460_i_i_fu_334_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

