# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_pin.xdc

# Block Designs: bd/sys_design/sys_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design || ORIG_REF_NAME==sys_design} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_processing_system7_0_0/sys_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design_processing_system7_0_0 || ORIG_REF_NAME==sys_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_pwm_ip_0_0/sys_design_pwm_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design_pwm_ip_0_0 || ORIG_REF_NAME==sys_design_pwm_ip_0_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_ps7_0_axi_periph_0/sys_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==sys_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_rst_ps7_0_50M_0/sys_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sys_design/ip/sys_design_auto_pc_0/sys_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sys_design_auto_pc_0 || ORIG_REF_NAME==sys_design_auto_pc_0} -quiet] -quiet

# XDC: bd/sys_design/ip/sys_design_processing_system7_0_0/sys_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_processing_system7_0_0 || ORIG_REF_NAME==sys_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/sys_design/ip/sys_design_rst_ps7_0_50M_0/sys_design_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_design/ip/sys_design_rst_ps7_0_50M_0/sys_design_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==sys_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==sys_design_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/sys_design/ip/sys_design_auto_pc_0/sys_design_auto_pc_0_ooc.xdc

# XDC: bd/sys_design/sys_design_ooc.xdc
